package com.example.quizzapp.quizzAppDb;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.quizzapp.quizzAppDb.Language;
import com.example.quizzapp.quizzAppDb.QuizzUser;
import com.example.quizzapp.quizzAppDb.Result;

import com.example.quizzapp.quizzAppDb.LanguageDao;
import com.example.quizzapp.quizzAppDb.QuizzUserDao;
import com.example.quizzapp.quizzAppDb.ResultDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig languageDaoConfig;
    private final DaoConfig quizzUserDaoConfig;
    private final DaoConfig resultDaoConfig;

    private final LanguageDao languageDao;
    private final QuizzUserDao quizzUserDao;
    private final ResultDao resultDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        languageDaoConfig = daoConfigMap.get(LanguageDao.class).clone();
        languageDaoConfig.initIdentityScope(type);

        quizzUserDaoConfig = daoConfigMap.get(QuizzUserDao.class).clone();
        quizzUserDaoConfig.initIdentityScope(type);

        resultDaoConfig = daoConfigMap.get(ResultDao.class).clone();
        resultDaoConfig.initIdentityScope(type);

        languageDao = new LanguageDao(languageDaoConfig, this);
        quizzUserDao = new QuizzUserDao(quizzUserDaoConfig, this);
        resultDao = new ResultDao(resultDaoConfig, this);

        registerDao(Language.class, languageDao);
        registerDao(QuizzUser.class, quizzUserDao);
        registerDao(Result.class, resultDao);
    }
    
    public void clear() {
        languageDaoConfig.clearIdentityScope();
        quizzUserDaoConfig.clearIdentityScope();
        resultDaoConfig.clearIdentityScope();
    }

    public LanguageDao getLanguageDao() {
        return languageDao;
    }

    public QuizzUserDao getQuizzUserDao() {
        return quizzUserDao;
    }

    public ResultDao getResultDao() {
        return resultDao;
    }

}
